### ISSUE TITLE
this duplicates (badly) the pass functionality

### ISSUE THREAD

**Issue by johnypony3** [ahnick/encpass.sh#10]
there is a gold standard for this which integrates directly with git
https://www.passwordstore.org

good luck!

**Comment by ahnick** [comment]
Since, other people will likely wonder about this as well, I'll go ahead and respond.  I'll even leave this issue open until I have time to add this to a FAQ or README.

First things first, I wrote encpass.sh unaware that pass even existed.  It wasn't until someone on HN mentioned it did I even know about it.  Having examined pass, I concur that it looks like great software. If you are looking for a personal password manager I would definitely recommend going with pass.

encpass.sh is something I threw together with the specific goal of making it dead simple to use encrypted passwords in shell scripts.  It is specifically focused on that use case and it's design reflects that.  Many times when putting together scripts I just wanted something that was quick to include and didn't add lots of dependencies for my script.  If this is your use case, then encpass.sh may be appropriate for you. 

With this use case in mind, let me list the items where I think encpass.sh adds value:
- It is super simple to include or bundle with your own scripts.  Just curl the script to your path or local directory and keep hacking.  There's no initialization process or installation really.
- The first time the script tries to retrieve a secret that doesn't exist it prompts for the secret and then stores it for subsequent times.  The developer doesn't have to leave their current flow to insert passwords to the store.
- It is striving to be POSIX compliant, so it will work in a wide variety of shells.  I don't know if this is a priority for pass.  (it looks like it has support for bash, zsh, and fish, but I'm not sure beyond that?)  With encpass.sh I'd like to support as many shells as possible, so people who are constrained for one reason or another or prefer another shell can still use encpass.sh.
- encpass.sh depends on OpenSSL whereas pass depends on GPG.  OpenSSL, in my experience, tends to already be installed on lots of machines, so encpass.sh is more likely to work immediately without additional software to install.  Again, potentially critical if you aren't administering the machine where the script is running.
- encpass.sh now defaults to using unique symmetric keys per script.  pass does support this, but this isn't the default behavior.

In addition to those items, I also have some other features planned for encpass.sh that I don't think pass would ever probably include.  Being able to add the features I want is a nice benefit.  :-)  I think that while there is a lot of overlap with pass, there is enough differentiation in the implementations that encpass.sh provides a real benefit in the shell script use case.  Maybe others feel the same way?

**Comment by etopeter** [comment]
Encpass is very lightweight. It requires only openssl and posix shell - that's it, you can concentrate on your scripts. 
Pass has a lot more dependencies like gnupg, gnu getopt, xclip which makes it a lot less portable.

**Comment by ahnick** [comment]
I also think allowing pass to be an optional backend for encpass.sh would be useful for people who use or plan to use pass.  This would allow people with pass passwords to use the syntactic sugar that encpass.sh provides in their scripts and access to features (planned for the future) that encpass.sh provides that pass does not.  I wouldn't want to replicate all functionality that pass provides, but where there is overlap we should be able to easily map to an equivalent pass command.

**Comment by johnypony3** [comment]
thanks for the write up! definitely nice to not have to init. i do like that i can have my passwords across my devices.

**Comment by HackInTheBox** [comment]
I'm new to coding, but very aware of the issues that secure encryption creates.  This is a great script for me to learn from.. and to use as a basis for other app.  There are more uses for this, such as a "quiz" game or any other app which needs to hide info from the end user.... with some modifications.  :)
