### ISSUE TITLE
Confusing positional parameters for get_secret

### ISSUE THREAD

**Issue by etopeter** [ahnick/encpass.sh#9]
With newest changes we're using function get_secret param1 param2 are confusing. 
Current behavior:
if I put get_secret param1 I will get secret param1 for label of current script name
if I put get_secret param1 param2 I will get secret param2 for label param1
if i put get_secret (without parameters) I will get secret "password" and label script name
param1 and param2 meaning changes depending on number of parameters.

Positional parameters should always mean the same. Since this function is used by programmers we should require all parameters. This way it always clear what password you're getting/setting. Default settings could be set for command line interface users.

```
 if [ ! -z $1 ] && [ ! -z $2 ]; then
                LABEL=$1
                SECRET_NAME=$2
        elif [ ! -z $1 ]; then
                LABEL=$(basename $0)
                SECRET_NAME=$1
...
```

**Comment by ahnick** [comment]
@etopeter So this was by design as I want this solution to be really fast and simple to use in scripts.  If I'm a developer working on a script and I just want my password to be encrypted, then I don't want to necessarily have to care about scoping it to a label and coming up with a name for my password.  It's simpler for the developer to just call the method and have it take care of it for him/her in that particular case. The pattern is basically the same as using method overloading (https://en.wikipedia.org/wiki/Function_overloading), which is pretty widely used.  I certainly understand the argument you are making, but the main philosophy for encpass.sh is to be super lightweight and make reasonable opinionated choices for the user to achieve low friction.  Once encpass.sh starts becoming more saddled with options and required fields, then it loses some of its attractiveness as a simple solution.  It's definitely a trade-off.
